bridges_main:
    resource: "@BridgesMainBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: es|en|   # needs to be null in case no /language is provided

# bridges_main_second:
#     resource: "@BridgesMainBundle/Resources/config/routing.yml"
#     prefix:   /

bridges_user:
    resource: "@BridgesUserBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/admin/
    requirements:
        _locale: es|en

# bridges_user_second:
#     resource: "@BridgesUserBundle/Resources/config/routing.yml"
#     prefix:   /admin/

# USERs

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix:     /{_locale}/profile
    requirements:
        _locale: es|en

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix:     /{_locale}/register
    requirements:
        _locale: es|en

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix:     /{_locale}/resetting
    requirements:
        _locale: es|en

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix:     /{_locale}/changePassword
    requirements:
        _locale: es|en


# Redactor 
bridges_redactor:
    resource: "@BridgesRedactorBundle/Controller/"
    type:     annotation
    prefix:   /redactor/
