jms_security_extra:
    secure_all_services: false
    expressions: true


security:
    encoders:
        Bridges\UserBundle\Entity\User: sha512   #plaintext pour aucun encodage
        # Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        main:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                always_use_default_target_path: true
                default_target_path: /%locale%/admin
            logout:
                path:       fos_user_security_logout
                target:     /%locale%/
            remember_me:
                key:        %secret% # %secret% est un paramètre de parameters.yml

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/es/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/es/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/es/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/es/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: [IS_AUTHENTICATED_REMEMBERED,ROLE_ADMIN] }
        - { path: ^/es/admin, role: [IS_AUTHENTICATED_REMEMBERED,ROLE_ADMIN] }
        - { path: ^/en/admin, role: [IS_AUTHENTICATED_REMEMBERED,ROLE_ADMIN] }

