<?php

namespace Bridges\MainBundle\Entity;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
	public function findLatestOne() {
		return $this->createQueryBuilder('p')
					->orderBy('p.updatedAt', 'DESC')
					->setMaxResults(1)
					->getQuery()
					->getResult();
	}
}
